CREATE TABLE IF NOT EXISTS `Country` (
    ID INT NOT NULL AUTO_INCREMENT,
    CODE VARCHAR(255),
    NAME VARCHAR(255),
    CONTINENT VARCHAR(255),
    WIKIPEDIA_LINK VARCHAR(255),
    KEYWORDS VARCHAR(1000),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS `Airport` (
    ID INT NOT NULL AUTO_INCREMENT,
    IDENT VARCHAR(255),
    TYPE VARCHAR(255),
    NAME VARCHAR(255),
    LATITUDE_DEG DOUBLE,
    LONGITUDE_DEG DOUBLE,
    ELEVATION_FT VARCHAR(255),
    CONTINENT VARCHAR(255),
    ISO_COUNTRY VARCHAR(255),
    ISO_REGION VARCHAR(255),
    MUNICIPALITY VARCHAR(255),
    SCHEDULED_SERVICE VARCHAR(255),
    GPS_CODE VARCHAR(255),
    IATA_CODE VARCHAR(255),
    LOCAL_CODE VARCHAR(255),
    HOME_LINK VARCHAR(255),
    WIKIPEDIA_LINK VARCHAR(255),
    KEYWORDS VARCHAR(1000),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS `Runway` (
    ID INT NOT NULL AUTO_INCREMENT,
    AIRPORT_REF INT,
    AIRPORT_IDENT VARCHAR(255),
    LENGTH_FT INT,
    WIDTH_FT INT,
    SURFACE VARCHAR(255),
    LIGHTED BOOLEAN,
    CLOSED BOOLEAN,
    LE_IDENT VARCHAR(255),
    LE_LATITUDE_DEG VARCHAR(255),
    LE_LONGITUDE_DEG VARCHAR(255),
    LE_ELEVATION_FT VARCHAR(255),
    LE_HEADING_DEGT VARCHAR(255),
    LE_DISPLACED_THRESHOLD_FT VARCHAR(255),
    HE_IDENT VARCHAR(255),
    HE_LATITUDE_DEG VARCHAR(255),
    HE_LONGITUDE_DEG VARCHAR(255),
    HE_ELEVATION_FT VARCHAR(255),
    HE_HEADING_DEGT VARCHAR(255),
    HE_DISPLACED_THRESHOLD_FT VARCHAR(255),
    PRIMARY KEY (ID),
    FOREIGN KEY (AIRPORT_REF) REFERENCES Airport(ID)
);


INSERT INTO Country (ID, CODE, NAME, CONTINENT, WIKIPEDIA_LINK, KEYWORDS) VALUES (1, 'GR', 'GREECE', '', '', '');
INSERT INTO Country (ID, CODE, NAME, CONTINENT, WIKIPEDIA_LINK, KEYWORDS) VALUES (2, 'NL', 'NETHERLANDS', '', '', '');
INSERT INTO Country (ID, CODE, NAME, CONTINENT, WIKIPEDIA_LINK, KEYWORDS) VALUES (3, 'BG', 'BELGIUM', '', '', '');

INSERT INTO Airport (ID, IDENT, TYPE, NAME, LATITUDE_DEG, LONGITUDE_DEG, ELEVATION_FT, CONTINENT, ISO_COUNTRY, ISO_REGION,
                     MUNICIPALITY, SCHEDULED_SERVICE, GPS_CODE, IATA_CODE, LOCAL_CODE, HOME_LINK, WIKIPEDIA_LINK, KEYWORDS)
VALUES (1, 'ident', 'type', 'Airport1', 10.5, 11.2, '', '', 'GR', '', '', '', '', '', '', '', '', '');

INSERT INTO Airport (ID, IDENT, TYPE, NAME, LATITUDE_DEG, LONGITUDE_DEG, ELEVATION_FT, CONTINENT, ISO_COUNTRY, ISO_REGION,
                     MUNICIPALITY, SCHEDULED_SERVICE, GPS_CODE, IATA_CODE, LOCAL_CODE, HOME_LINK, WIKIPEDIA_LINK, KEYWORDS)
VALUES (2, 'ident', 'type', 'Airport2', 20.5, 21.2, '', '', 'GR', '', '', '', '', '', '', '', '', '');

INSERT INTO Airport (ID, IDENT, TYPE, NAME, LATITUDE_DEG, LONGITUDE_DEG, ELEVATION_FT, CONTINENT, ISO_COUNTRY, ISO_REGION,
                     MUNICIPALITY, SCHEDULED_SERVICE, GPS_CODE, IATA_CODE, LOCAL_CODE, HOME_LINK, WIKIPEDIA_LINK, KEYWORDS)
VALUES (3, 'ident', 'type', 'Airport1', 30.5, 31.2, '', '', 'NL', '', '', '', '', '', '', '', '', '');

INSERT INTO Runway (ID, AIRPORT_REF, AIRPORT_IDENT, LENGTH_FT, WIDTH_FT, SURFACE, LIGHTED, CLOSED, LE_IDENT, LE_LATITUDE_DEG,
                    LE_LONGITUDE_DEG, LE_ELEVATION_FT, LE_HEADING_DEGT, LE_DISPLACED_THRESHOLD_FT, HE_IDENT, HE_LATITUDE_DEG,
                    HE_LONGITUDE_DEG, HE_ELEVATION_FT, HE_HEADING_DEGT, HE_DISPLACED_THRESHOLD_FT)
VALUES (1, 1, 'ident', 10, 10, 'surface', true, false, '', '', '', '', '', '', '', '', '', '', '', '');

INSERT INTO Runway (ID, AIRPORT_REF, AIRPORT_IDENT, LENGTH_FT, WIDTH_FT, SURFACE, LIGHTED, CLOSED, LE_IDENT, LE_LATITUDE_DEG,
                    LE_LONGITUDE_DEG, LE_ELEVATION_FT, LE_HEADING_DEGT, LE_DISPLACED_THRESHOLD_FT, HE_IDENT, HE_LATITUDE_DEG,
                    HE_LONGITUDE_DEG, HE_ELEVATION_FT, HE_HEADING_DEGT, HE_DISPLACED_THRESHOLD_FT)
VALUES (2, 2, 'ident', 20, 20, 'surface', true, false, '', '', '', '', '', '', '', '', '', '', '', '');

INSERT INTO Runway (ID, AIRPORT_REF, AIRPORT_IDENT, LENGTH_FT, WIDTH_FT, SURFACE, LIGHTED, CLOSED, LE_IDENT, LE_LATITUDE_DEG,
                    LE_LONGITUDE_DEG, LE_ELEVATION_FT, LE_HEADING_DEGT, LE_DISPLACED_THRESHOLD_FT, HE_IDENT, HE_LATITUDE_DEG,
                    HE_LONGITUDE_DEG, HE_ELEVATION_FT, HE_HEADING_DEGT, HE_DISPLACED_THRESHOLD_FT)
VALUES (3, 3, 'ident', 30, 30, 'surface', true, false, '', '', '', '', '', '', '', '', '', '', '', '');