CREATE TABLE IF NOT EXISTS `Country` (
    ID INT NOT NULL AUTO_INCREMENT,
    CODE VARCHAR(255),
    NAME VARCHAR(255),
    CONTINENT VARCHAR(255),
    WIKIPEDIA_LINK VARCHAR(255),
    KEYWORDS VARCHAR(1000),
    PRIMARY KEY (ID)
) AS SELECT * FROM CSVREAD('classpath:/csv/countries.csv');

CREATE INDEX COUNTRY_NAME ON Country(NAME);
CREATE INDEX COUNTRY_CODE ON Country(CODE);

CREATE TABLE IF NOT EXISTS `Airport` (
    ID INT NOT NULL AUTO_INCREMENT,
    IDENT VARCHAR(255),
    TYPE VARCHAR(255),
    NAME VARCHAR(255),
    LATITUDE_DEG DOUBLE,
    LONGITUDE_DEG DOUBLE,
    ELEVATION_FT VARCHAR(255),
    CONTINENT VARCHAR(255),
    ISO_COUNTRY VARCHAR(255),
    ISO_REGION VARCHAR(255),
    MUNICIPALITY VARCHAR(255),
    SCHEDULED_SERVICE VARCHAR(255),
    GPS_CODE VARCHAR(255),
    IATA_CODE VARCHAR(255),
    LOCAL_CODE VARCHAR(255),
    HOME_LINK VARCHAR(255),
    WIKIPEDIA_LINK VARCHAR(255),
    KEYWORDS VARCHAR(1000),
    PRIMARY KEY (ID)
) AS SELECT * FROM CSVREAD('classpath:/csv/airports.csv');

CREATE INDEX AIRPORT_ID ON Airport(ID);

CREATE TABLE IF NOT EXISTS `Runway` (
    ID INT NOT NULL AUTO_INCREMENT,
    AIRPORT_REF INT,
    AIRPORT_IDENT VARCHAR(255),
    LENGTH_FT INT,
    WIDTH_FT INT,
    SURFACE VARCHAR(255),
    LIGHTED BOOLEAN,
    CLOSED BOOLEAN,
    LE_IDENT VARCHAR(255),
    LE_LATITUDE_DEG VARCHAR(255),
    LE_LONGITUDE_DEG VARCHAR(255),
    LE_ELEVATION_FT VARCHAR(255),
    LE_HEADING_DEGT VARCHAR(255),
    LE_DISPLACED_THRESHOLD_FT VARCHAR(255),
    HE_IDENT VARCHAR(255),
    HE_LATITUDE_DEG VARCHAR(255),
    HE_LONGITUDE_DEG VARCHAR(255),
    HE_ELEVATION_FT VARCHAR(255),
    HE_HEADING_DEGT VARCHAR(255),
    HE_DISPLACED_THRESHOLD_FT VARCHAR(255),
    PRIMARY KEY (ID),
    FOREIGN KEY (AIRPORT_REF) REFERENCES Airport(ID)
) AS SELECT * FROM CSVREAD('classpath:/csv/runways.csv');

CREATE INDEX RUNWAY_ID ON Runway(ID);